# Generated by Django 2.1.3 on 2018-11-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=True, choices=[(1, 'Afrikaans\n'), (2, 'Albanian\n'), (3, 'Amharic\n'), (4, 'Arabic (Egyptian Spoken)\n'), (5, 'Arabic (Levantine)\n'), (6, 'Arabic (Modern Standard)\n'), (7, 'Arabic (Moroccan Spoken)\n'), (8, 'Arabic (Overview)\n'), (9, 'Aramaic\n'), (10, 'Armenian\n'), (11, 'Assamese\n'), (12, 'Aymara\n'), (13, 'Azerbaijani\n'), (14, 'Balochi\n'), (15, 'Bamanankan\n'), (16, 'Bashkort (Bashkir)\n'), (17, 'Basque\n'), (18, 'Belarusan\n'), (19, 'Bengali\n'), (20, 'Bhojpuri\n'), (21, 'Bislama\n'), (22, 'Bosnian\n'), (23, 'Brahui\n'), (24, 'Bulgarian\n'), (25, 'Burmese\n'), (26, 'Cantonese\n'), (27, 'Catalan\n'), (28, 'Cebuano\n'), (29, 'Chechen\n'), (30, 'Cherokee\n'), (31, 'Croatian\n'), (32, 'Czech\n'), (33, 'Dakota\n'), (34, 'Danish\n'), (35, 'Dari\n'), (36, 'Dholuo\n'), (37, 'Dutch\n'), (38, 'English\n'), (39, 'Esperanto\n'), (40, 'Estonian\n'), (41, 'Éwé\n'), (42, 'Finnish\n'), (43, 'French\n'), (44, 'Georgian\n'), (45, 'German\n'), (46, 'Gikuyu\n'), (47, 'Greek\n'), (48, 'Guarani\n'), (49, 'Gujarati\n'), (50, 'Haitian Creole\n'), (51, 'Hausa\n'), (52, 'Hawaiian\n'), (53, 'Hawaiian Creole\n'), (54, 'Hebrew\n'), (55, 'Hiligaynon\n'), (56, 'Hindi\n'), (57, 'Hungarian\n'), (58, 'Icelandic\n'), (59, 'Igbo\n'), (60, 'Ilocano\n'), (61, 'Indonesian (Bahasa Indonesia)\n'), (62, 'Inuit/Inupiaq\n'), (63, 'Irish Gaelic\n'), (64, 'Italian\n'), (65, 'Japanese\n'), (66, 'Jarai\n'), (67, 'Javanese\n'), (68, 'K’iche’\n'), (69, 'Kabyle\n'), (70, 'Kannada\n'), (71, 'Kashmiri\n'), (72, 'Kazakh\n'), (73, 'Khmer\n'), (74, 'Khoekhoe\n'), (75, 'Korean\n'), (76, 'Kurdish\n'), (77, 'Kyrgyz\n'), (78, 'Lao\n'), (79, 'Latin\n'), (80, 'Latvian\n'), (81, 'Lingala\n'), (82, 'Lithuanian\n'), (83, 'Macedonian\n'), (84, 'Maithili\n'), (85, 'Malagasy\n'), (86, 'Malay (Bahasa Melayu)\n'), (87, 'Malayalam\n'), (88, 'Mandarin (Chinese)\n'), (89, 'Marathi\n'), (90, 'Mende\n'), (91, 'Mongolian\n'), (92, 'Nahuatl\n'), (93, 'Navajo\n'), (94, 'Nepali\n'), (95, 'Norwegian\n'), (96, 'Ojibwa\n'), (97, 'Oriya\n'), (98, 'Oromo\n'), (99, 'Pashto\n'), (100, 'Persian\n'), (101, 'Polish\n'), (102, 'Portuguese\n'), (103, 'Punjabi\n'), (104, 'Quechua\n'), (105, 'Romani\n'), (106, 'Romanian\n'), (107, 'Russian\n'), (108, 'Rwanda\n'), (109, 'Samoan\n'), (110, 'Sanskrit\n'), (111, 'Serbian\n'), (112, 'Shona\n'), (113, 'Sindhi\n'), (114, 'Sinhala\n'), (115, 'Slovak\n'), (116, 'Slovene\n'), (117, 'Somali\n'), (118, 'Spanish\n'), (119, 'Swahili\n'), (120, 'Swedish\n'), (121, 'Tachelhit\n'), (122, 'Tagalog\n'), (123, 'Tajiki\n'), (124, 'Tamil\n'), (125, 'Tatar\n'), (126, 'Telugu\n'), (127, 'Thai\n'), (128, 'Tibetic languages\n'), (129, 'Tigrigna\n'), (130, 'Tok Pisin\n'), (131, 'Turkish\n'), (132, 'Turkmen\n'), (133, 'Ukrainian\n'), (134, 'Urdu\n'), (135, 'Uyghur\n'), (136, 'Uzbek\n'), (137, 'Vietnamese\n'), (138, 'Warlpiri\n'), (139, 'Welsh\n'), (140, 'Wolof\n'), (141, 'Xhosa\n'), (142, 'Yakut\n'), (143, 'Yiddish\n'), (144, 'Yoruba\n'), (145, 'Yucatec\n'), (146, 'Zapotec\n'), (147, 'Zulu\n')], default=38, help_text='Choose Language')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
    ]
